### ISSUE TITLE
System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by mrfroncu** [hadeutscher/OvercookedTool#14]
`
E:\Downloads\OvercookedTool1.0>.\OvercookedTool.exe decrypt C:\Users\Matthew\AppData\LocalLow\Team17\Overcooked2\XXXXXXXXXXXXXXXXXXXXXXX\Meta_SaveFile.save C:\Temp\Meta_SaveFile.json Epic.OnlineServices.EpicAccountId
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Temp\Meta_SaveFile.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at OvercookedPasten.Program.Decrypt(String source_filename, String dest_filename, String pwd) in D:\Data\Projects\OvercookedTool\OvercookedTool\Program.cs:line 262
   at OvercookedPasten.Program.Main(String[] args) in D:\Data\Projects\OvercookedTool\OvercookedTool\Program.cs:line 286
`

**Comment by zabbidou** [comment]
Check if the path contains any spaces or special characters (from what I see it doesn't, but that was the problem for me).
Also change the json path, maybe the "C:\Temp" is protected. Try Desktop or something else.

**Comment by lionboy88** [comment]
In addition to the above comment, also try changing the location of the OvercookedTool.exe folder. The code worked for me only once I changed the location of the tool. Maybe try putting it somewhere on C:\
